import { useState, useEffect } from "react";
import StoryCard from "@/components/StoryCard";
import StarField from "@/components/StarField";

interface Story {
  id: string;
  title: string;
  date: string;
  excerpt: string;
  content: string;
}

const Home = () => {
  const [stories, setStories] = useState<Story[]>([]);

  useEffect(() => {
    // Load stories from JSON
    fetch("/src/data/stories.json")
      .then((res) => res.json())
      .then((data) => {
        const sortedStories = data.sort(
          (a: Story, b: Story) => new Date(b.date).getTime() - new Date(a.date).getTime()
        );
        setStories(sortedStories);
      })
      .catch((error) => {
        console.error("Error loading stories:", error);
      });
  }, []);

  return (
    <div className="min-h-screen relative">
      <StarField />
      
      <div className="relative z-10 container mx-auto px-6 py-16">
        {/* Hero Section */}
        <div className="text-center mb-16 animate-fade-up">
          <h1 className="text-5xl md:text-6xl font-bold mb-4 text-foreground">
            🌙 Let's Get You Into Bed
          </h1>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            Dreamy AI stories, freshly spun every night.
          </p>
        </div>

        {/* Stories Grid */}
        {stories.length > 0 ? (
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8 max-w-7xl mx-auto">
            {stories.map((story, index) => (
              <StoryCard
                key={story.id}
                id={story.id}
                title={story.title}
                date={story.date}
                excerpt={story.excerpt}
                index={index}
              />
            ))}
          </div>
        ) : (
          <div className="text-center text-muted-foreground animate-scale-in">
            <p className="text-xl">No stories yet — check back at bedtime 🌜</p>
          </div>
        )}

        {/* Footer */}
        <footer className="text-center mt-24 text-muted-foreground text-sm animate-fade-up" style={{ animationDelay: "400ms" }}>
          <p>Generated by AI & crafted with care 🌌</p>
        </footer>
      </div>
    </div>
  );
};

export default Home;
